services:
  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - messenger-db-data:/code/app/db/data

volumes:
  messenger-db-data:
    driver: local
